package com.gerardo788.proyectofinal

import android.view.KeyCharacterMap
import java.util.*

data class Propiedades (
    val estado : String,
    val alcaldiaOMunicipio : String,
    val colonia : String,
    val codigoPostal : Int,
    val conjuntoOEdificio : String,
    val calle : String,
    val numExterior : Int,
    val numInterior : String,
    val tipoOperacion : Char,
    val tipoPropiedad : String,
    val precioEn : String,
    val cantidad : Double,
    val amueblado : Char,
    val electrodomesticos : Char,
    val factura : Char,
    val nombreAsesor : String,
    val comision : String,
    val fechaProxContacto : Date,
    val comentarios : String,
    val numeroRecamaras : Int,
    val bañosCompletos : Int,
    val mediosBaños : Int,
    val numeroEstacionamientos : Int,
    val metrosCuadradosTerreno : Double,
    val metrosCuadradosConstruccion : Double,
    val numeroNivelDondeSeEncuentra : Int,
    val numeroTotalNivelesEdificio : Int,
    val edadInmueble : Int,
    val estudio : Char,
    val salaTV : Char,
    val balcon : Char,
    val terraza : Char,
    val jardinPrivadoDeInmueble : Char,
    val cuartoServicio : Char,
    val cocina : Char,
    val tipoPisoEstancia : Char,
    val tipoPisoRecamaras : Char,
    val tipoPisoBanos : Char,
    val tipoPisoCocina : Char,
    val aireAcondicionado : Char,
    val calefaccion : Char,
    val alberca : Char,
    val gimnasio : Char,
    val jardin : Char,
    val canchaTenis : Char,
    val spinning : Char,
    val pistaCorrer : Char,
    val areaJuegosNinos : Char,
    val salonUsosMultiples : Char,
    val salonFiestas: Char,
    val clubGolf : Char,
    val areaMascotas : Char,
    val bodega : Char,
    val admitenMascotas : Char,
    val vigilancia : Char,
    val mantenimientoIncluido : Char,
    val costoMantenimiento : Char,
    val caracteristicasExtras : Char,
    val textoParaPublicidad : Char,
    val nombrePropietario : Char,
    val telefonoCasa : Int,
    val telefonoCelular : Int,
    val telefonoOficina : Int,
    val correoElectronico : String,
    val nombreAsistente : String,
    val telefonoAsistente : Int,

    )
{

}